name: mynest
dependencies:
  - python=3.10.8
  - psycopg2
  - pip=22.3.1
  - pip:
      - django==4.1.1
      - djangorestframework==3.14.0
      - djangorestframework_simplejwt==5.2.2
      - drf_yasg==1.21.4
      - gunicorn
      - flake8==6.0.0
      - pillow==9.3.0
