# Generated by Django 4.1.1 on 2023-02-01 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('TB', 'to buy'), ('IP', 'in progress'), ('BO', 'bought')], default='TB', max_length=2)),
                ('favorite', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.home')),
            ],
        ),
    ]
