# Generated by Django 4.1.1 on 2023-02-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('TD', 'todo'), ('IP', 'in progress'), ('DO', 'done')], default='TD', max_length=2)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
