# Generated by Django 4.1.1 on 2023-02-05 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='planned_for',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
