# Generated by Django 4.1.1 on 2023-02-02 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category', models.IntegerField(choices=[(1, 'GROCERIES'), (2, 'MAINTENANCE'), (3, 'UTILITIES'), (4, 'HOUSEHOLD_SUPPLIES'), (5, 'OTHER')], default=5)),
                ('amount', models.FloatField()),
                ('bill_image', models.ImageField(blank=True, max_length=255, upload_to='')),
                ('created', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
    ]
