# Generated by Django 4.1.1 on 2023-02-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, upload_to='', verbose_name='avatar'),
        ),
    ]
