# Generated by Django 4.1.1 on 2023-02-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='My Nest')),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
